[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pandastock"
version = "0.0.6"
description = "Pandas extension for financial data processing and visualization"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "GPL-3.0-or-later"}
authors = [
    { name="Alexey Sheshukov", email="alexeyshesh@yandex.ru"}
]
keywords = ["pandas", "finance", "trading", "candlestick", "technical-indicators", "visualization", "stock", "charting"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Developers",
    "Topic :: Office/Business :: Financial",
    "Topic :: Scientific/Engineering :: Visualization",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas",
    "matplotlib"
]

[project.urls]
Homepage = "https://github.com/alexeyshesh/pandastock"
Repository = "https://github.com/alexeyshesh/pandastock"
Issues = "https://github.com/alexeyshesh/pandastock/issues"

[tool.setuptools.packages.find]
include = ["pandastock*"]
